### ISSUE TITLE
Regression in recent versions

### ISSUE THREAD

**Issue by Coobaha** [onurkerimov/xoid#3]
Hi @onurkerimov, first of all thanks for xoid :) enjoying its simplicity

I've noticed that this code stopped propagating react updates 

```typescript
import { create, use } from "xoid";
import { useAtom } from "@xoid/react";

const state = create({ key: null });

const slice = use(state, (s) => s.key);

const useSlice = () => useAtom(slice);

// passing identity selector fixes it 
const useSliceWorks = () => useAtom(slice, s => s);

const useSliceWorksToo = () => useAtom(state, (s) => s.key);

// this is not triggering re-renders of useSlice inside React ctx
// but useSliceWorks is working
const setSlice = (value) => slice(value);
```

so using `useSlice+setSlice` is not causing re-renders anymore, but `useSliceWorks` is correctly updated

**Comment by Coobaha** [comment]
I tried to make a simple isolated repro, but it works with React 18.2 and recent version of `xoid` packages 🤔

**Comment by Coobaha** [comment]
@onurkerimov while I can't build a minimal reproduction of this  - i still observe this in our codebase (which is private :/) But I've noticed that passing selector to useAtom fixes it, even identity `(x => x)`

**Comment by onurkerimov** [comment]
@Coobaha In the 1.0.0-beta.0 release, this problem was also considered. The internal subscription API and selector mechanism is changed. There shouldn't be a problem with not providing a selector function now.

Also a note on the new API; The changes are breaking changes, and the old API is not supported anymore, however usage with React remains pretty similar. `useAtom`'s second argument no longer takes a selector. Instead, `.focus` method is used.
>Before
```js
useAtom($atom, (s) => s.key);
```
>After
```js
useAtom($atom.focus((s) => s.key));
```

I'm going to close this issue if a similar problem doesn't get reported soon.

**Comment by Coobaha** [comment]
Great! I will close it for now. Thanks!
